import AdminNavbar from "../_components/AdminNavbar";
import AdminSidebar from "../_components/AdminSidebar";
import { Inter } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import { cookies } from "next/headers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen">
      <div className="bg-slate-600">
        <AdminSidebar />
      </div>

      <div className="w-full bg-slate-100 p-5">
        <AdminNavbar />
        {children}
      </div>
    </div>
  );
}
