import "~/styles/globals.css";

import Header from "./_components/Header";
import { Inter } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "./_components/ui/toaster";
import { headers } from "next/headers";
import { Web3Provider } from "./_components/ClientProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} flex min-h-screen flex-1 flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]`}
      >
        <TRPCReactProvider headers={headers()}>
          <Web3Provider>
            <Header />
            <main className="flex flex-1 items-center justify-center text-white">
              {children}
            </main>
          </Web3Provider>
        </TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}
